= Scoring Subsystem
:toc: left

== Summary

The scoring subsystem contains the xref:shooter.adoc[Shooter] and Indexer.

Currently, the scoring subsystem does not include the Intake. However, it may be deemed beneficial that the scoring subsystem also includes the intake, to better coordinate intaking and scoring actions between the intake and the indexer-shooter combination. This decision will be made after the intake is implemented and more work is done on the scoring state machine.

== State Machine

The scoring subsystem state machine will now (tentatively) have 5 states, 4 of which will be used during competition:

=== 1. Idle

Indexer will target its bottom position, and the shooter wheels will stop.

This state can only be exited by an external trigger to warm up.

=== 2. Warmup

The shooter wheels will accelerate toward their target angular velocity. The indexer will remain in its bottom position.

This state can exited when:

* The driver releases the warmup trigger (right trigger)/stops warming up.
* The shooter is "ready" (at its goal RPM) and one of the following is true:
** The driver is pressing the "shoot" button (right bumper).
** Pose-based shooting is enabled and the shot is currently attainable (see xref:shooter.adoc#determining-shooterspeeds[Shooter/Determining Shooter Speeds]).
* The robot is ready to score if scoring semi-autonomously (semi-autonomous scoring has yet to be designed)

=== 3. Kick

The shooter wheels continue targeting their goal speeds to score, while the indexer begins moving upward to "kick" the algae into the shooter wheels.

This state will be left when the indexer gets near the top of its motion.

=== 4. Wait to Score

This state holds the indexer at the top for a short period of time while the shooter wheels continue to spin to make sure that the algae has time to completely leave the robot before returning to idle. Returning to idle too early would result in weak, inconsistent shots.

This state will be active for a certain configurable period of time and then will transition back to idle.

=== 5. Tuning

This state will be automatically entered and exited whenever the tuning mode changes to or from a scoring tuning mode. This state will stop the motors and send the indexer to idle position on entry, after which it won't send any controls to avoid interfering with test modes.

== Public API

=== Ready-to-Intake Supplier

A boolean function indicating if the indexer is at the bottom of its range of motion. If the indexer is not at the bottom, the robot will be unable to safely intake and readyToIntake will return false.

=== Fire Trigger method

This method is exposed publicly for 2 reasons:

==== 1. To be used in button bindings (e.g. to start warming up).
==== 2. For use in states, which are implemented outside of the ScoringSubsystem class itself.

=== Control Methods

A handful of public methods that should only be called from within states to allow the states to execute their actions:

- `stopIndexing` - Command bottom position for indexer
- `stopShooter` - Command zero velocity for wheels
- `startHomingIndexer`- Drive the indexer to the bottom of its range of motion using open-loop control to home it into hardstop.
- `warmupShooter()` - Spin up the shooter wheels to get ready to shoot. The speeds are determined by the xref:shooter.adoc[Shooter].
- `indexIntoShooter()` - Command the indexer to the top of its range of motion.


[#decisions-tbd,reftext=TBD]
== Decisions Yet To Be Made

- It must be decided whether, in addition to the "score" button which scores whenever the shooter is ready, there should exist a "force score" button which will blindly fire the kicker regardless of whether or not the flywheels are at their target speeds.