= Shooter
:toc: left

== Summary

The shooter has 2 flywheels. These flywheels will be controlled using closed-loop control through Motion Magic Velocity and drive the motors with Torque-Current Field Oriented Control

== Public API

The shooter provides two main methods for control, which should be called by (and only by) the Scoring Subsystem:

=== Stop

Stops the shooter motors.

=== Warm Up

Based on whether or not pose-based shooting is currently enabled, either calculate the currently accurate set of speeds or run the shooter at the predefined fallback set of speeds.

This method will actually configure the shooter's "current action" to be warming up. This means that it will run the calculations automatically in every periodic loop, so even if `warmUp` isn't called periodically it will still behave correctly.

This was previously `runSpeeds` but it was replaced since the determination of shooter speeds is the responsibility of the Shooter itself, not any other subsystem and therefore placing that code anywhere else would cause unnecessary clutter.

=== Tuning Periodic

This method will read LoggedTunableNumbers for each PID and Feedforward gain. If the tuning mode specifies a manual control output, it will read either the voltage or the current and apply it. If it specifies closed loop control, it will read shooter speeds and set them as its goal speeds.

== Tuning Modes

The shooter has various tuning modes to tune gains and test the system. It is recommended to use Elastic Dashboard to interact with the LoggedTunableNumbers published. The shooter defines 3 tuning modes:

=== Shooter closed loop tuning

This mode will read PID & FeedForward gains from NetworkTables and use them to control to a setpoint specified for each motor goal speed (also read from NetworkTables).

Gains will be published and read from NetworkTables at the path `/SmartDashboard/TunableNumbers/ShooterTunables/K[P,I,D,S,V,A]`. The target RPM for closed-loop control of each shooter side is will be published and read from NetworkTables at the paths `/SmartDashboard/TunableNumbers/ShooterTunables/[Left/Right]TargetRPM`. These LoggedTunableNumbers are checked and updated every periodic cycle.

=== Shooter voltage tuning

Manually specify a voltage for each shooter wheel via NetworkTables. This is useful for quick testing and prototyping.

Voltage numbers will be published and then continually read from NetworkTables at the paths `/SmartDashboard/TunableNumbers/ShooterTunables/[Left/Right]ManualVolts`. These values will be updated every periodic cycle if changed.

=== Shooter current tuning

Manually specify a torque-current for each shooter wheel via NetworkTables. This mode can be used to determine kS gain and quickly test motors.

Voltage numbers will be published and then continually read from NetworkTables at the paths `/SmartDashboard/TunableNumbers/ShooterTunables/[Left/Right]ManualAmps`. These values will be updated every periodic cycle if changed.