package frc.robot.subsystems.descorer;

import static edu.wpi.first.units.Units.Amps;
import static edu.wpi.first.units.Units.RadiansPerSecond;
import static edu.wpi.first.units.Units.Rotations;
import static edu.wpi.first.units.Units.RotationsPerSecond;
import static edu.wpi.first.units.Units.VoltsPerRadianPerSecond;
import static edu.wpi.first.units.Units.VoltsPerRadianPerSecondSquared;

import coppercore.parameter_tools.LoggedTunableNumber;
import coppercore.wpilib_interface.UnitUtils;
import edu.wpi.first.units.measure.Angle;
import edu.wpi.first.units.measure.MutAngle;
import frc.robot.TestModeManager;
import frc.robot.constants.JsonConstants;
// generated by chatgpt
import org.littletonrobotics.junction.Logger;

public class DeScorerSubsystem {
  PivotIO io;
  PivotIOInputsAutoLogged inputs = new PivotIOInputsAutoLogged();
  PivotIOInputsAutoLogged outputs = new PivotIOInputsAutoLogged();

  MutAngle goalAngle = Rotations.mutable(0.0);
  MutAngle clampedGoalAngle = Rotations.mutable(0.0);

  MutAngle minAngle = JsonConstants.pivotConstants.pivotMinAngle.mutableCopy();
  MutAngle maxAngle = JsonConstants.pivotConstants.pivotMaxAngle.mutableCopy();

  LoggedTunableNumber pivotkP;
  LoggedTunableNumber pivotkI;
  LoggedTunableNumber pivotkD;

  LoggedTunableNumber pivotkS;
  LoggedTunableNumber pivotkV;
  LoggedTunableNumber pivotkA;
  LoggedTunableNumber pivotkG;

  LoggedTunableNumber pivotCruiseVelocity;
  LoggedTunableNumber pivotExpokV;
  LoggedTunableNumber pivotExpokA;

  LoggedTunableNumber pivotTuningSetpointRotations;
  LoggedTunableNumber pivotTuningOverrideAmps;

  public DeScorerSubsystem(PivotIO io) {
    pivotkP =
        new LoggedTunableNumber("PivotTunables/pivotkP", JsonConstants.pivotConstants.pivotKP);
    pivotkI =
        new LoggedTunableNumber("PivotTunables/pivotkI", JsonConstants.pivotConstants.pivotKI);
    pivotkD =
        new LoggedTunableNumber("PivotTunables/pivotkD", JsonConstants.pivotConstants.pivotKD);

    pivotkS =
        new LoggedTunableNumber("PivotTunables/pivotkS", JsonConstants.pivotConstants.pivotKS);
    pivotkV =
        new LoggedTunableNumber("PivotTunables/pivotkV", JsonConstants.pivotConstants.pivotKV);
    pivotkA =
        new LoggedTunableNumber("PivotTunables/pivotkA", JsonConstants.pivotConstants.pivotKA);
    pivotkG =
        new LoggedTunableNumber("PivotTunables/pivotkG", JsonConstants.pivotConstants.pivotKG);

    pivotCruiseVelocity =
        new LoggedTunableNumber(
            "PivotTunables/pivotCruiseVelocity",
            JsonConstants.pivotConstants.pivotMotionMagicCruiseVelocity.in(RotationsPerSecond));
    pivotExpokV =
        new LoggedTunableNumber(
            "PivotTunables/pivotExpokV", JsonConstants.pivotConstants.pivotMotionMagicExpo_kV);
    pivotExpokA =
        new LoggedTunableNumber(
            "PivotTunables/pivotExpokA", JsonConstants.pivotConstants.pivotMotionMagicExpo_kA);

    pivotTuningSetpointRotations =
        new LoggedTunableNumber("PivotTunables/pivotTuningSetpointRotations", 0.0);
    pivotTuningOverrideAmps = new LoggedTunableNumber("WristTunables/wristTuningOverrideAmps", 0.0);

    this.io = io;
  }

  /**
   * Runs periodically when the robot is enabled
   *
   * <p>Does NOT run automatically! Must be called by the subsystem
   */
  public void periodic() {
    sendGoalAngleToIO();

    io.updateInputs(inputs);
    io.applyOutputs(outputs);

    Logger.processInputs("pivot/inputs", inputs);
    Logger.processInputs("pivot/outputs", outputs);
  }

  /** This method must be called from the subsystem's test periodic! */
  public void testPeriodic() {
    switch (TestModeManager.getTestMode()) {
      case PivotClosedLoopTuning:
        io.setOverrideMode(false);
        LoggedTunableNumber.ifChanged(
            hashCode(),
            (pid) -> {
              io.setPID(pid[0], pid[1], pid[2]);
            },
            pivotkP,
            pivotkI,
            pivotkD);

        LoggedTunableNumber.ifChanged(
            hashCode(),
            (ff) -> {
              io.setFF(ff[0], ff[1], ff[2], ff[3]);
            },
            pivotkS,
            pivotkV,
            pivotkA,
            pivotkG);

        LoggedTunableNumber.ifChanged(
            hashCode(),
            (maxProfile) -> {
              io.setMaxProfile(
                  RadiansPerSecond.of(0.0),
                  VoltsPerRadianPerSecondSquared.ofNative(maxProfile[0]),
                  VoltsPerRadianPerSecond.ofNative(maxProfile[1]));
            },
            pivotExpokA,
            pivotExpokV);

        LoggedTunableNumber.ifChanged(
            hashCode(),
            (setpoint) -> {
              setGoalAngle(Rotations.of(setpoint[0]));
            },
            pivotTuningSetpointRotations);
        break;
      case PivotCurrentTuning:
        LoggedTunableNumber.ifChanged(
            hashCode(),
            (setpoint) -> {
              io.setOverrideCurrent(Amps.of(setpoint[0]));
            },
            pivotTuningOverrideAmps);
        io.setOverrideMode(true);
        break;
      default:
        break;
    }
  }

  public void sendGoalAngleToIO() {
    updateClampedGoalAngle();

    io.setPivotGoalPos(clampedGoalAngle);
  }

  /**
   * Based on the bounds previously set, clamp the last set goal height to be between the bounds.
   *
   * <p>If the goal height is outside of the bounds and the bounds are expanded, this function will
   * still behave as expected, as the mechanism remembers its unclamped goal height and will attempt
   * to get there once it is allowed.
   */
  private void updateClampedGoalAngle() {
    clampedGoalAngle.mut_replace(UnitUtils.clampMeasure(goalAngle, minAngle, maxAngle));

    Logger.recordOutput("wrist/clampedGoalAngle", clampedGoalAngle);
  }

  /**
   * Set the goal angle the wrist will to control about.
   *
   * <p>This goal angle will be clamped by the allowed range of motion
   *
   * @param goalAngle The new goal angle
   */
  public void setGoalAngle(Angle goalAngle) {
    this.goalAngle.mut_replace(goalAngle);

    Logger.recordOutput("wrist/goalAngle", goalAngle);
  }

  /**
   * Sets the minimum and maximum allowed angles that the wrist may target.
   *
   * <p>When not in override mode, the goal angle of the wrist will be clamped to be between these
   * values before it is sent to the IO. When these clamps change, the original goal angle is
   * clamped to be within the new bounds.
   *
   * @param minAngle The minimum angle, which will be clamped between wristMinMinAngle and
   *     wristMaxMaxAngle before being applied
   * @param maxAngle The maximum angle, which will be clamped between wristMinMinAngle and
   *     wristMaxMaxAngle before being applied
   */
  public void setAllowedRangeOfMotion(Angle minAngle, Angle maxAngle) {
    setMinAngle(minAngle);
    setMaxAngle(maxAngle);
  }

  /**
   * Sets the minimum allowed angle that the wrist may target.
   *
   * <p>When not in override mode, the goal angle of the wrist will be clamped to be between these
   * values before it is sent to the IO. When these clamps change, the original goal angle is
   * clamped to be within the new bounds.
   *
   * @param minAngle The minimum angle, which will be clamped between wristMinMinAngle and
   *     wristMaxMaxAngle before being applied
   */
  public void setMinAngle(Angle minAngle) {
    this.minAngle.mut_replace(
        UnitUtils.clampMeasure(
            minAngle,
            JsonConstants.pivotConstants.pivotMinAngle,
            JsonConstants.pivotConstants.pivotMaxAngle));

    Logger.recordOutput("wrist/minAngle", minAngle);
  }

  /**
   * Sets the maximum allowed angle that the wrist may target.
   *
   * <p>When not in override mode, the goal angle of the wrist will be clamped to be between these
   * values before it is sent to the IO. When these clamps change, the original goal angle is
   * clamped to be within the new bounds.
   *
   * @param maxAngle The maximum angle, which will be clamped between wristMinMinAngle and
   *     wristMaxMaxAngle before being applied
   */
  public void setMaxAngle(Angle maxAngle) {
    this.maxAngle.mut_replace(
        UnitUtils.clampMeasure(
            maxAngle,
            JsonConstants.pivotConstants.pivotMaxAngle,
            JsonConstants.pivotConstants.pivotMaxAngle));

    Logger.recordOutput("wrist/maxAngle", maxAngle);
  }

  /**
   * Get the current angle of the wrist
   *
   * @return
   */
  public Angle getPivotAngle() {
    return inputs.pivotPosition;
  }

  /**
   * Get a reference to the wrist's IO. This should be used to update PID, motion profile, and feed
   * forward gains, and to set brake mode/disable motors. This method exists to avoid the need to
   * duplicate all of these functions between the mechanism and the IO.
   *
   * @return the wrist mechanism's IO
   */
  public PivotIO getIO() {
    return io;
  }

  /** Set whether or not the motor on the wrist should be disabled */
  public void setMotorsDisabled(boolean disabled) {
    io.setMotorsDisabled(disabled);
  }
}
