package frc.robot.subsystems.descorer;

import static edu.wpi.first.units.Units.Amps;
import static edu.wpi.first.units.Units.Rotations;

import com.ctre.phoenix6.StatusSignal;
import com.ctre.phoenix6.configs.CurrentLimitsConfigs;
import com.ctre.phoenix6.configs.FeedbackConfigs;
import com.ctre.phoenix6.configs.MotionMagicConfigs;
import com.ctre.phoenix6.configs.MotorOutputConfigs;
import com.ctre.phoenix6.configs.Slot0Configs;
import com.ctre.phoenix6.configs.TalonFXConfiguration;
import com.ctre.phoenix6.configs.TorqueCurrentConfigs;
import com.ctre.phoenix6.controls.MotionMagicExpoVoltage;
import com.ctre.phoenix6.controls.TorqueCurrentFOC;
import com.ctre.phoenix6.controls.VoltageOut;
import com.ctre.phoenix6.hardware.TalonFX;
import com.ctre.phoenix6.signals.GravityTypeValue;
import com.ctre.phoenix6.signals.NeutralModeValue;

import edu.wpi.first.units.AngularAccelerationUnit;
import edu.wpi.first.units.AngularVelocityUnit;
import edu.wpi.first.units.VoltageUnit;
import edu.wpi.first.units.measure.Angle;
import edu.wpi.first.units.measure.AngularVelocity;
import edu.wpi.first.units.measure.Current;
import edu.wpi.first.units.measure.MutAngle;
import edu.wpi.first.units.measure.MutCurrent;
import edu.wpi.first.units.measure.Per;
import frc.robot.constants.JsonConstants;
import frc.robot.subsystems.descorer.WheelIO.WheelIOInputs;

public class WheelIOTalonFX implements WheelIO{
    TalonFX wheelMotor = new TalonFX(JsonConstants.wheelConstants.wheelMotorId);
    StatusSignal<Angle> wheelPosition = wheelMotor.getRotorPosition(); // line of code generated by
  // chatgpt(But I don't think it works) so I
  // changed it(Idk how the plagarism thing works) Also this is copied from the pivot one so IDK even more
    StatusSignal<AngularVelocity> wheelVelocity = wheelMotor.getRotorVelocity();

    private TalonFXConfiguration talonFXConfigs;

    private MutAngle wheelGoalPosition = Rotations.mutable(0.0); // placeholder

    private MotionMagicExpoVoltage request = new MotionMagicExpoVoltage(wheelGoalPosition);

    private boolean motorsDisabled = false;

    private boolean isOverriding = false;

    private MutCurrent overrideCurrent = Amps.mutable(0.0);
    public WheelIOTalonFX() {
    talonFXConfigs =
        new TalonFXConfiguration()
            .withFeedback(
                new FeedbackConfigs()
                    .withFeedbackRemoteSensorID(JsonConstants.wheelConstants.wheelRotorSensorId)
                    .withSensorToMechanismRatio(
                        JsonConstants.wheelConstants.sensorToMechanismRatio))
            .withMotorOutput(
                new MotorOutputConfigs()
                    .withNeutralMode(JsonConstants.wheelConstants.wheelNeutralModeValue))
            .withCurrentLimits(
                new CurrentLimitsConfigs()
                    .withSupplyCurrentLimitEnable(true)
                    .withSupplyCurrentLimit(JsonConstants.wheelConstants.wheelSupplyCurrentLimit)
                    .withStatorCurrentLimitEnable(true)
                    .withStatorCurrentLimit(JsonConstants.wheelConstants.wheelStatorCurrentLimit))
            .withTorqueCurrent(
                new TorqueCurrentConfigs()
                    .withPeakForwardTorqueCurrent(JsonConstants.wheelConstants.peakFOCCurrent)
                    .withPeakReverseTorqueCurrent(JsonConstants.wheelConstants.peakFOCCurrent))
            .withSlot0(
                new Slot0Configs()
                    .withKG(JsonConstants.wheelConstants.wheelKG)
                    .withKS(JsonConstants.wheelConstants.wheelKS)
                    .withKV(JsonConstants.wheelConstants.wheelKV)
                    .withKA(JsonConstants.wheelConstants.wheelKA)
                    .withKP(JsonConstants.wheelConstants.wheelKP)
                    .withKI(JsonConstants.wheelConstants.wheelKI)
                    .withKD(JsonConstants.wheelConstants.wheelKD)
                    //.withGravityType(GravityTypeValue.Arm_Cosine)
                    )
            .withMotionMagic(
                new MotionMagicConfigs()
                    .withMotionMagicCruiseVelocity(
                        JsonConstants.wheelConstants.wheelMotionMagicCruiseVelocity)
                    .withMotionMagicExpo_kA(JsonConstants.wheelConstants.wheelMotionMagicExpo_kA)
                    .withMotionMagicExpo_kV(JsonConstants.wheelConstants.wheelMotionMagicExpo_kV));
    wheelMotor.getConfigurator().apply(talonFXConfigs);
  }
  public void updateInputs(WheelIOInputs inputs) {
    inputs.wheelGoalPosition.mut_replace(wheelGoalPosition);
    inputs.wheelSetpointPosition.mut_replace(
        Rotations.of(wheelMotor.getClosedLoopReference().getValue()));
    StatusSignal<Angle> positionSignal = wheelMotor.getRotorPosition();
    inputs.connected = positionSignal.getStatus().isOK();
    inputs.wheelPosition.mut_replace(wheelPosition.getValue());
    inputs.wheelVelocity.mut_replace(wheelVelocity.getValue());

    inputs.wheelTargetVelocity.mut_setMagnitude(
        wheelMotor.getClosedLoopReferenceSlope().getValue());

    inputs.wheelSupplyCurrent.mut_replace(wheelMotor.getSupplyCurrent().getValue());
    inputs.wheelStatorCurrent.mut_replace(wheelMotor.getStatorCurrent().getValue());
  }

  public void applyOutputs(WheelIOInputs outputs) {
    if (motorsDisabled) {
      wheelMotor.setControl(new VoltageOut(0.0));
      outputs.wheelClosedLoopOutput = 0.0;
      return;

    } else if (isOverriding) {
      wheelMotor.setControl(new TorqueCurrentFOC(overrideCurrent));
      outputs.wheelClosedLoopOutput = overrideCurrent.in(Amps);

      return;
    }
    wheelMotor.setControl(request.withPosition(wheelGoalPosition));
    outputs.wheelClosedLoopOutput = wheelMotor.getClosedLoopOutput().getValue();
  }

  public void setWheelGoalPos(Angle goalPos) {
    wheelGoalPosition.mut_replace(goalPos);
  }

  public void setPID(double kP, double kI, double kD) {
    talonFXConfigs.Slot0.kP = kP; // check if im slot zero
    talonFXConfigs.Slot0.kI = kI;
    talonFXConfigs.Slot0.kD = kD;

    wheelMotor.getConfigurator().apply(talonFXConfigs);
  }

  public void setMaxProfile(
      AngularVelocity maxVelocity,
      Per<VoltageUnit, AngularAccelerationUnit> expo_kA,
      Per<VoltageUnit, AngularVelocityUnit> expo_kV) {
    talonFXConfigs.withMotionMagic(
        new MotionMagicConfigs()
            .withMotionMagicCruiseVelocity(maxVelocity)
            .withMotionMagicExpo_kA(expo_kA)
            .withMotionMagicExpo_kV(expo_kV));
    wheelMotor.getConfigurator().apply(talonFXConfigs);
  }

  public void setFF(double kS, double kV, double kA, double kG) {
    talonFXConfigs.Slot0.kS = kS;
    talonFXConfigs.Slot0.kV = kV;
    talonFXConfigs.Slot0.kA = kA;
    talonFXConfigs.Slot0.kG = kG;

    wheelMotor.getConfigurator().apply(talonFXConfigs);
  }

  public void setBrakeMode(boolean brakeMode) {
    if (brakeMode) {
      talonFXConfigs.MotorOutput.NeutralMode = NeutralModeValue.Brake;
    } else {
      talonFXConfigs.MotorOutput.NeutralMode = NeutralModeValue.Coast;
    }

    wheelMotor.getConfigurator().apply(talonFXConfigs);
  }

  public void setCurrentLimits(CurrentLimitsConfigs limits) {
    talonFXConfigs.withCurrentLimits(limits);

    wheelMotor.getConfigurator().apply(talonFXConfigs);
  }

  public void setMotorsDisabled(boolean disabled) {
    motorsDisabled = disabled;
  }

  public void setOverrideMode(boolean override) {
    isOverriding = override;
  }

  public void setOverrideCurrent(Current current) {
    overrideCurrent.mut_replace(current);
  }
}
