package frc.robot.subsystems.descorer;

import static edu.wpi.first.units.Units.KilogramSquareMeters;
import static edu.wpi.first.units.Units.Radians;
import static edu.wpi.first.units.Units.RadiansPerSecond;
import static edu.wpi.first.units.Units.Seconds;

import org.littletonrobotics.junction.Logger;

import com.ctre.phoenix6.configs.CurrentLimitsConfigs;
import com.ctre.phoenix6.sim.TalonFXSimState;

import edu.wpi.first.math.numbers.N1;
import edu.wpi.first.math.system.LinearSystem;
import edu.wpi.first.math.system.plant.DCMotor;
import edu.wpi.first.units.AngularAccelerationUnit;
import edu.wpi.first.units.AngularVelocityUnit;
import edu.wpi.first.units.VoltageUnit;
import edu.wpi.first.units.measure.Angle;
import edu.wpi.first.units.measure.AngularVelocity;
import edu.wpi.first.units.measure.MutAngle;
import edu.wpi.first.units.measure.Per;
import edu.wpi.first.wpilibj.RobotController;
import edu.wpi.first.wpilibj.simulation.FlywheelSim; // generated by chatgpt
import edu.wpi.first.wpilibj.simulation.SingleJointedArmSim;
import frc.robot.constants.JsonConstants;
import frc.robot.constants.SimConstants;
import frc.robot.subsystems.descorer.PivotIO.PivotIOInputs;
import frc.robot.subsystems.descorer.WheelIO.WheelIOInputs;

public class WheelIOSim extends WheelIOTalonFX {
  TalonFXSimState wheelMotorSimState = wheelMotor.getSimState();

  //lines 26-40 are generated by chatgpt
//These numbers should be right(Although I am scared about freeSpeed)
double nominalVoltage = 24.0;      // volts
double stallTorque = 4.05;          // N·m
double stallCurrent = 275.0;       // amps
double freeCurrent = 1.4;          // amps
double freeSpeed = 7530.0 * 2 * Math.PI / 60.0; // rad/s 

DCMotor krakenX44Foc = new DCMotor(
    nominalVoltage,
    stallTorque,
    stallCurrent,
    freeCurrent,
    freeSpeed,
    1 // number of motors
);
  private final FlywheelSim wheelSim =
      new FlywheelSim(
          krakenX44Foc,
          JsonConstants.wheelConstants.wheelReduction,
          JsonConstants.wheelConstantsSim.wheelMomentOfInertia.in(KilogramSquareMeters),
          RadiansPerSecond.of(1e-3));

  public WheelIOSim() {
    super();

    // Initialize sim state so that the first periodic runs with accurate data
    updateSimState();
  }


  private void updateSimState() {
    AngularVelocity wheelVelocity = RadiansPerSecond.of(wheelSim.getAngularVelocityRadPerSec());

    Angle spinAngle; //placeholder for how much we spin

    wheelMotorSimState.addRotorPosition(spinAngle); // line of code generated by chatgpt
    wheelMotorSimState.setRotorVelocity(
        wheelVelocity); // idk if this math is still easy also generated by chatgpt

    Angle rotorDiffAngle = spinAngle.times(JsonConstants.wheelConstants.wheelReduction);
    AngularVelocity rotorVelocity =
        wheelVelocity.times(JsonConstants.wheelConstants.wheelReduction);

    wheelMotorSimState.addRotorPosition(rotorDiffAngle);
    wheelMotorSimState.setRotorVelocity(rotorVelocity);
    wheelMotorSimState.setSupplyVoltage(RobotController.getBatteryVoltage());

    wheelSim.setInputVoltage(wheelMotorSimState.getMotorVoltage());
  }

  @Override
  public void updateInputs(WheelIOInputs inputs) {
    updateSimState();

    wheelSim.update(SimConstants.simDeltaTime.in(Seconds));

    super.updateInputs(inputs);
  }
  
}
